Data Cleaning of the social movement survey data

```{r}
#install.packages('lubridate')
library(lubridate)
library(tidyverse)
```


```{r}
raw <- read.csv('all_apps_wide-2022-09-12_1004.csv', header=T)

raw[['participant.time_started_utc']] <- strptime(raw[['participant.time_started_utc']],
                                                  format = '%Y-%m-%d %H:%M:%OS',
                                                  tz = 'utc')
op <- options(digits.secs=6)
#attr(raw$participant.time_started_utc, 'tzone') <- 'CET'
#with_tz(raw$participant.time_started_utc, "CET")

as.POSIXlt(raw$participant.time_started_utc, tz = 'CET')
```

Cleaning 2.0

```{r}
# drop observations 
raw1 <- raw %>% filter(participant._is_bot !=1  # recognised as bot
                        ,survey_example_appfolder.1.player.time_welcome != -999  # did not start survey
                        ,survey_example_appfolder.1.player.time_endpage != -999  # did not end survey
                        , ! is.na(participant.label) # no participant label
                        )

```

Data Formatting
```{r}

raw1 <- raw1 %>% mutate( #convert times
                          survey_example_appfolder.1.player.time_welcome =
                          as.POSIXlt(survey_example_appfolder.1.player.time_welcome, 
                                   format = '%Y-%m-%dT%H:%M:%S',
                                   tz = 'utc')
                        , survey_example_appfolder.1.player.time_quotapage =
                          strptime(survey_example_appfolder.1.player.time_quotapage, 
                                   format = '%Y-%m-%dT%H:%M:%S',
                                   tz = 'utc')
                        , survey_example_appfolder.1.player.time_endpage =
                          strptime(survey_example_appfolder.1.player.time_endpage, 
                                   format = '%Y-%m-%dT%H:%M:%S',
                                   tz = 'utc')
                        , survey_example_appfolder.1.player.sm_time_treatmentpage =
                          strptime(survey_example_appfolder.1.player.sm_time_treatmentpage, 
                                   format = '%Y-%m-%dT%H:%M:%S',
                                   tz = 'utc')
                        , survey_example_appfolder.1.player.sm_time_demonstrationpage =
                          strptime(survey_example_appfolder.1.player.sm_time_demonstrationpage, 
                                   format = '%Y-%m-%dT%H:%M:%S',
                                   tz = 'utc')
                        , survey_example_appfolder.1.player.sm_time_participationpage =
                          strptime(survey_example_appfolder.1.player.sm_time_participationpage, 
                                   format ='%Y-%m-%dT%H:%M:%S',
                                   tz = 'utc')
                        , survey_example_appfolder.1.player.sm_time_politicalpage =
                          strptime(survey_example_appfolder.1.player.sm_time_politicalpage, 
                                   format = '%Y-%m-%dT%H:%M:%S',
                                   tz = 'utc')
                        # rename variables before dropping ba/ch variables
                        , location = survey_example_appfolder.1.player.ba_location
                        , immigration1 = survey_example_appfolder.1.player.ba_immigration1
                        , immigration2 = survey_example_appfolder.1.player.ba_immigration2
                        , immigration3 = survey_example_appfolder.1.player.ba_immigration3) 

# time needed for the full survey
raw1$starttofinish <- raw1$survey_example_appfolder.1.player.time_endpage -
                      raw1$survey_example_appfolder.1.player.time_welcome 

raw1 <- raw1 %>% filter(starttofinish <=120)

save(raw1, file = "raw_all.RData")
```

```{r}
# drop all variables of other groups
columns_ba <- grep("survey_example_appfolder.1.player.ba", names(raw1))
raw2 <- raw1 %>% select(-columns_ba) 

columns_ch <- grep("survey_example_appfolder.1.player.ch", names(raw2))
raw2 <- raw2 %>% select(-columns_ch) 


# drop prefix from column names
names(raw2) <- sub('^survey_example_appfolder.1.player.', '', names(raw2))

save(raw2, file = "raw_no_ba_ch.RData")
```

```{r}
# convert social movement and other relevant variables to factors
raw3 <-raw2 %>% mutate(across(
                              c(sm_group_assignment,
                                sm_participation ,
                                sm_topic_relevance,
                                sm_familiar_people,
                                sm_booked,
                                sm_transportation,
                                sm_reach,
                                sm_number,
                                sm_crowd,
                                sm_polarization,
                                sm_riots,
                                sm_missing_knowledge,
                                sm_own_knowledge,
                                sm_general_knowledge,
                                sm_future,
                                sm_unsure,
                                sm_olddays,
                                sm_demonstration_change,
                                sm_demonstration_democracy,
                                sm_demonstration_views,
                                sm_politicians,
                                sm_influence,
                                sm_interests,
                                therm_spd,
                                therm_cdu,
                                therm_csu,
                                therm_gruene,
                                therm_fdp,
                                therm_afd,
                                therm_linke,
                                household_income,
                                general_education,
                                eligibility,
                                participation,
                                demonstration_participation_allowed,
                                demonstration_participation_notallowed,
                                demonstration_participation_online,
                                social_media,
                                device_type,
                                operating_system),
                              as.factor))
                                  
save(raw3, file = "raw_factor.RData")

# turn missing (-999) and "weiß nicht" (-888) answers to NA
df <- raw3 %>% mutate(across(where(is.factor), ~na_if(., -999)),
                        across(where(is.factor), ~na_if(., -888)))

save(df, file = "online_exp_df.RData")
```


